// This file would typically be auto-generated by Supabase CLI
// using: supabase gen types typescript --local > src/types/database.ts
// For now, this is a simplified version for development

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          subscription_plan: 'starter' | 'professional' | 'enterprise'
          monthly_document_limit: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          subscription_plan?: 'starter' | 'professional' | 'enterprise'
          monthly_document_limit?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          subscription_plan?: 'starter' | 'professional' | 'enterprise'
          monthly_document_limit?: number
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          organization_id: string | null
          email: string
          full_name: string | null
          role: 'admin' | 'attorney' | 'paralegal' | 'client'
          department: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          organization_id?: string | null
          email: string
          full_name?: string | null
          role?: 'admin' | 'attorney' | 'paralegal' | 'client'
          department?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          organization_id?: string | null
          email?: string
          full_name?: string | null
          role?: 'admin' | 'attorney' | 'paralegal' | 'client'
          department?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      documents: {
        Row: {
          id: string
          user_id: string
          organization_id: string | null
          file_name: string
          file_type: string | null
          file_size: number | null
          file_url: string | null
          document_type: string | null
          status: 'pending' | 'processing' | 'completed' | 'error'
          created_at: string
          processed_at: string | null
          metadata: Json
        }
        Insert: {
          id?: string
          user_id: string
          organization_id?: string | null
          file_name: string
          file_type?: string | null
          file_size?: number | null
          file_url?: string | null
          document_type?: string | null
          status?: 'pending' | 'processing' | 'completed' | 'error'
          created_at?: string
          processed_at?: string | null
          metadata?: Json
        }
        Update: {
          id?: string
          user_id?: string
          organization_id?: string | null
          file_name?: string
          file_type?: string | null
          file_size?: number | null
          file_url?: string | null
          document_type?: string | null
          status?: 'pending' | 'processing' | 'completed' | 'error'
          created_at?: string
          processed_at?: string | null
          metadata?: Json
        }
      }
      analyses: {
        Row: {
          id: string
          document_id: string
          extraction_data: Json
          analysis_data: Json
          risks: Json
          action_items: Json
          time_saved: number | null
          cost_saved: number | null
          confidence: number | null
          processing_time: number | null
          created_at: string
        }
        Insert: {
          id?: string
          document_id: string
          extraction_data: Json
          analysis_data: Json
          risks?: Json
          action_items?: Json
          time_saved?: number | null
          cost_saved?: number | null
          confidence?: number | null
          processing_time?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          document_id?: string
          extraction_data?: Json
          analysis_data?: Json
          risks?: Json
          action_items?: Json
          time_saved?: number | null
          cost_saved?: number | null
          confidence?: number | null
          processing_time?: number | null
          created_at?: string
        }
      }
      action_items: {
        Row: {
          id: string
          analysis_id: string | null
          document_id: string | null
          assigned_to: string | null
          title: string
          description: string | null
          priority: 'urgent' | 'high' | 'medium' | 'low'
          status: 'pending' | 'in-progress' | 'completed'
          due_date: string | null
          estimated_hours: number | null
          completed_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          analysis_id?: string | null
          document_id?: string | null
          assigned_to?: string | null
          title: string
          description?: string | null
          priority?: 'urgent' | 'high' | 'medium' | 'low'
          status?: 'pending' | 'in-progress' | 'completed'
          due_date?: string | null
          estimated_hours?: number | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          analysis_id?: string | null
          document_id?: string | null
          assigned_to?: string | null
          title?: string
          description?: string | null
          priority?: 'urgent' | 'high' | 'medium' | 'low'
          status?: 'pending' | 'in-progress' | 'completed'
          due_date?: string | null
          estimated_hours?: number | null
          completed_at?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      processing_metrics: {
        Row: {
          id: string
          document_id: string | null
          user_id: string | null
          organization_id: string | null
          processing_time: number | null
          time_saved: number | null
          cost_saved: number | null
          confidence: number | null
          document_type: string | null
          created_at: string
        }
        Insert: {
          id?: string
          document_id?: string | null
          user_id?: string | null
          organization_id?: string | null
          processing_time?: number | null
          time_saved?: number | null
          cost_saved?: number | null
          confidence?: number | null
          document_type?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          document_id?: string | null
          user_id?: string | null
          organization_id?: string | null
          processing_time?: number | null
          time_saved?: number | null
          cost_saved?: number | null
          confidence?: number | null
          document_type?: string | null
          created_at?: string
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          type: string
          title: string
          message: string | null
          read: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          type?: string
          title: string
          message?: string | null
          read?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          title?: string
          message?: string | null
          read?: boolean
          created_at?: string
        }
      }
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          action: string
          resource_type: string | null
          resource_id: string | null
          details: Json
          ip_address: string | null
          user_agent: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id?: string | null
          action: string
          resource_type?: string | null
          resource_id?: string | null
          details?: Json
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string | null
          action?: string
          resource_type?: string | null
          resource_id?: string | null
          details?: Json
          ip_address?: string | null
          user_agent?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      dashboard_metrics: {
        Row: {
          organization_id: string
          organization_name: string
          total_documents: number
          active_users: number
          total_time_saved: number
          total_cost_saved: number
          avg_processing_time: number
          avg_confidence: number
        }
      }
      team_usage: {
        Row: {
          department: string | null
          documents_processed: number
          time_saved: number
          avg_processing_time: number
          most_common_doc_type: string | null
        }
      }
    }
    Functions: {
      get_organization_metrics: {
        Args: {
          p_org_id: string
          p_days?: number
        }
        Returns: {
          total_documents: number
          total_time_saved: number
          total_cost_saved: number
          active_users: number
          avg_processing_time: number
          avg_confidence: number
        }[]
      }
      track_api_usage: {
        Args: {
          p_org_id: string
          p_provider: string
          p_endpoint: string
          p_tokens: number
          p_cost: number
        }
        Returns: void
      }
    }
  }
}
